# Generated by Django 5.1.5 on 2025-02-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_created_at_role_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
